### ISSUE TITLE
Update layout of Single Page by ID

### ISSUE THREAD

**Issue by orbitrod** [bentideswell/magento2-wordpress-integration#84] opened 2019-01-03 16:17 UTC
I was reviewing the Layout XML documentation, [here]( https://fishpig.co.uk/magento/wordpress-integration/layout-xml/), and I was wondering if it is possible to `remove` or `move` blocks and containers of a specific page?  

I tried the XML below to remove the `breadcrumbs` block from a page with an ID of 432, but it did not work.
```
<wordpress_page_view_432>
<referenceBlock name="breadcrumbs" remove="true" />
</wordpress_page_view_432>
```

**Comment by bentideswell** [comment] 2019-01-04 09:36
Hi @orbitrod, you're mixing Magento 1 layout XML with Magento 2.

Layout handles (eg. <wordpress_page_view_432>) belong in Magento 1. In Magento 2, this would be a file named wordpress_page_view_432.xml and then you would have XML like:

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
  <body>
    <referenceBlock name="breadcrumbs" remove="true" />
  </body>
</page>
```

I will close this issue as this is not a bug in the module. Feel free to contact me at help@fishpig.co.uk, however I recommend reading several tutorials on Magento layout XML. Layout XML updates in the FishPig_WordPress module are no different from layout XML updates for any Magento module. The only difference is the block names and layout file names.

**Closed by bentideswell** 2019-01-04 09:36 UTC
