### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by akosweb** [bentideswell/magento2-wordpress-integration#15] opened 2016-08-19 00:38 UTC
Get an error when I try di compile: 

`Source class "\FishPig\WordPress\Model\App" for "FishPig\WordPress\Model\App\Factory" generation does not exist.  `

And Magento backend throws:

`Invalid block type: FishPig\WordPress\Block\System\Config\Integrate
#0 /var/www/public/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('FishPig\\WordPre...', Array)
#1 /var/www/public/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(216): Magento\Framework\View\Layout\Generator\Block->createBlock('FishPig\\WordPre...', 'wordpress.confi...', Array)
#2 /var/www/public/lib/internal/Magento/Framework/View/Layout/Generator/Block.php(124): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'wordpress.confi...')
#3 /var/www/public/lib/internal/Magento/Framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#4 /var/www/public/lib/internal/Magento/Framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#5 /var/www/public/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#6 /var/www/public/lib/internal/Magento/Framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#7 /var/www/public/lib/internal/Magento/Framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#8 /var/www/public/lib/internal/Magento/Framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#9 /var/www/public/lib/internal/Magento/Framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#10 /var/www/public/lib/internal/Magento/Framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#11 /var/www/public/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#12 /var/www/public/app/code/Magento/Backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#13 /var/www/public/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Config:...')
#14 /var/www/public/app/code/Magento/Config/Controller/Adminhtml/System/Config/Edit.php(55): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Config:...')
#15 /var/www/public/var/generation/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php(25): Magento\Config\Controller\Adminhtml\System\Config\Edit->execute()
#16 /var/www/public/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->execute()
#17 /var/www/public/app/code/Magento/Backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/public/app/code/Magento/Config/Controller/Adminhtml/System/AbstractConfig.php(52): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#19 [internal function]: Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/public/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#21 /var/www/public/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callParent('dispatch', Array)
#22 /var/www/public/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'adminAuthentica...')
#23 /var/www/public/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#24 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/public/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#26 /var/www/public/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'designLoader')
#27 /var/www/public/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/public/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#30 /var/www/public/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Array, 'adminMassaction...')
#31 /var/www/public/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/public/lib/internal/Magento/Framework/Interception/Interceptor.php(143): call_user_func_array(Array, Array)
#34 /var/www/public/var/generation/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php(40): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /var/www/public/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/public/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#38 /var/www/public/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /var/www/public/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#40 /var/www/public/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#41 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /var/www/public/lib/internal/Magento/Framework/Interception/Interceptor.php(143): call_user_func_array(Array, Array)
#43 /var/www/public/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#44 /var/www/public/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#45 /var/www/public/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#46 /var/www/public/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#47 {main}`

**Comment by clivewalkden** [comment] 2016-09-07 13:36
My version successfully compiles without throwing any errors but when trying to visit any blog pages I get a 500 error and this in my PHP-FPM error log. Using Magento 2.0.7
`[07-Sep-2016 13:20:38 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to FishPig\WordPress_Multisite\Model\Plugin::__construct() must be an instance of FishPig\WordPress\Model\App, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/vhosts/**********/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 97 and defined in /var/www/vhosts/**********/magento/app/code/FishPig/WordPress_Multisite/Model/Plugin.php(1) : eval()'d code:14
Stack trace:
#0 /var/www/vhosts/**********/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(97): FishPig\WordPress_Multisite\Model\Plugin->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#1 /var/www/vhosts/**********/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Ma in /var/www/vhosts/**********/magento/app/code/FishPig/WordPress_Multisite/Model/Plugin.php(1) : eval()'d code on line 14
`

**Comment by bentideswell** [comment] 2016-09-22 08:52
I have just released updates for FishPig_WordPress and FishPig_WordPress_Multisite that should fix this issue. I will close this for now but re-open if the issue isn't resolved.

You can download FishPig_WordPress_Multisite from your account on https://fishpig.co.uk/

**Closed by bentideswell** 2016-09-22 08:52 UTC
