### ISSUE TITLE
Videos (YouTube and Vimeo) doesn't work

### ISSUE THREAD

**Issue by Krapulat** [bentideswell/magento2-wordpress-integration#68] opened 2017-12-28 11:24 UTC
When you insert a YouTube video (also happens with Vimeo) inside a post, it seems to work well in WordPress admin. But then in frontend simply show the URL and not the video embeded.

**Comment by bentideswell** [comment] 2017-12-28 11:29
Can you post the exact YouTube URL that you are using? Please post it exactly as you have included it in your post.

**Comment by Krapulat** [comment] 2017-12-28 11:34
@bentideswell It happens in all URLs I tried. But, for example, this one: https://www.youtube.com/watch?v=flqL3ySER64

**Comment by bentideswell** [comment] 2017-12-28 12:26
I've tried the URL and yes you're correct, it's not being parsed correctly. I have just released an update that fixes this issue. I will close this but please re-open or create a new ticket if the issue is not resolved.

**Closed by bentideswell** 2017-12-28 12:26 UTC

**Comment by Krapulat** [comment] 2017-12-28 12:34
Thanks. It works fine now!
