### ISSUE TITLE
Magento 2.3 Compatibility

### ISSUE THREAD

**Issue by iods** [bentideswell/magento2-wordpress-integration#97] opened 2020-01-08 18:13 UTC
Hi, there,

Just for clarification, this is compatible w/ the newest version of Magento (CE 2.3.3) correct?

Have you had reports of any issues w/ it's upgrade (M2.3)?

Have you had reports of any issues w/ a v1 to v2 of this plugin on a M2.3 instance?

Thanks for you work and time.

**Comment by bentideswell** [comment] 2020-01-09 10:00
Yes the module is compatible with Magento 2.3.3 and all versions of Magento 2.3 and will be compatible with Magento 2.3.4 when it is released shortly.

I will close this issue but feel free to re-open it if you have a specific error message or issue.

**Closed by bentideswell** 2020-01-09 10:00 UTC

**Comment by iods** [comment] 2020-02-14 21:47
Here is the error I am receiving with this:

`FishPig_WordPress.ERROR: FishPig\WordPress\Model\Integration\IntegrationException: Unable to install/upgrade the FishPig WordPress theme due to permissions. The file that triggered the error is /var/www/html/docroot/wp/wp-content/themes/fishpig/404.php in /var/www/html/docroot/vendor/bentideswell/magento2-wordpress-integration/Model/Integration/IntegrationException.php:22
Stack trace:
#0 /var/www/html/docroot/vendor/bentideswell/magento2-wordpress-integration/Model/Theme.php(179): FishPig\WordPress\Model\Integration\IntegrationException::throwException('Unable to insta...')
#1 /var/www/html/docroot/vendor/bentideswell/magento2-wordpress-integration/Model/Integration/ThemeTest.php(40): FishPig\WordPress\Model\Theme->validate()
#2 /var/www/html/docroot/vendor/bentideswell/magento2-wordpress-integration/Model/IntegrationManager.php(71): FishPig\WordPress\Model\Integration\ThemeTest->runTest()
#3 /var/www/html/docroot/vendor/bentideswell/magento2-wordpress-integration/Controller/Router.php(82): FishPig\WordPress\Model\IntegrationManager->runTests()
#4 /var/www/html/docroot/vendor/magento/framework/App/FrontController.php(95): FishPig\WordPress\Controller\Router->match(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/docroot/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/html/docroot/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#7 /var/www/html/docroot/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /var/www/html/docroot/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /var/www/html/docroot/app/code/Amasty/InvisibleCaptcha/Plugin/Predispatch.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/docroot/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\InvisibleCaptcha\Plugin\Predispatch->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/docroot/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/docroot/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/docroot/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/docroot/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#15 /var/www/html/docroot/vendor/magento/framework/App/Http.php(137): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/docroot/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#17 /var/www/html/docroot/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#18 {main} {"backtrace":{"file":"/var/www/html/docroot/vendor/bentideswell/magento2-wordpress-integration/Model/Theme.php","line":199,"function":"error","class":"Monolog\\Logger","type":"->"}} []`

**Comment by bentideswell** [comment] 2020-02-15 07:10
The error message literally tells you what the issue is:

**Unable to install/upgrade the FishPig WordPress theme due to permissions.**

The directory with insufficient permissions is the wp-content/themes/fishpig directory. Ensure that this directory has permissions so that the latest version of the FishPig theme can be auto installed.

If you do not want to change the permissions, you can manually copy contents from the wptheme folder of each FishPig module (currently on FishPig_WordPress and FishPig_WordPress_RelatedProducts have this folder) over to wp-content/themes/fishpig

**Comment by iods** [comment] 2020-02-17 19:59
My apologies, I should have made sure to add that this error is thrown when I have full ownership and privileges available on this folder. I also moved these over manually and am still getting this error. The other thing to mention, is that only two pages do not work. I can open up posts, lists of posts, etc. it is the category pages that will not render, and this is the only error thrown. Nothing else.

**Comment by bentideswell** [comment] 2020-02-18 07:51
Did you manage to resolve this? I had a GitHub notification saying you had replied but I can't find it so I'm not sure if you solved it and deleted the message.

Here's a little more info, based on your error message:

You can see the code/line that triggers the error:

https://github.com/bentideswell/magento2-wordpress-integration/blob/3f71957326473caf4c1f4b9121a1df341d918779/Model/Theme.php#L160,L163

It first checks to see whether the data needs to be updated (line 160) and then checks to see whether the location is writable. If it isn't writable then the error is thrown.

Manually copying the contents of vendor/fishpig/magento2-wordpress-integration/wptheme to wp-content/themes/fishpig/ should fix the issue.

**Comment by iods** [comment] 2020-02-21 17:27
My apologies, I should have been more descriptive:

We use a K8's cluster in our cloud to manage sites, which automatically manages our permissions on build through a bash script called during the creation of containers, what happened was there was a new file in the update from the version we had, that file was triggering the error. Sorry for sending a stupid question.

The issue seems to be the category pages, 503 to be exact, I am not getting errors on this which is why I was assuming the above was specific to an issue with an incorrect installation, thus creating an error displaying content. Other posts work, top-level categories do not.

**Comment by bentideswell** [comment] 2020-02-22 09:13
No worries! 

Did you update the plugin?

For the theme, it would probably be best to modify your build scripts to manually copy over the FishPig theme before setting the permissions. This would fix this issue as all of the files would be correct.

**Comment by bentideswell** [comment] 2020-02-22 09:14
Also, if you want to email me at help@fishpig.co.uk, I'd be happy to provide more direct support.
