### ISSUE TITLE
Fatal Error in prodyuction mode after dependencies generation and deployment of static content.

### ISSUE THREAD

**Issue by creatuitydevelopers** [bentideswell/magento2-wordpress-integration#17] opened 2016-09-20 13:12 UTC
We have encountered an error related to Multisite Integration extension. When Magento 2 is in production mode, has its dependencies generated and static content deployed we are unable to enter the blog page and the following Fatal Error occurs:

_Error message:_
`Fatal error: Uncaught TypeError: Argument 1 passed to FishPig\WordPress_Multisite\Model\Plugin::__construct() must be an instance of FishPig\WordPress\Model\App, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /var/www/some/path/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /var/www/some/path/app/code/FishPig/WordPress_Multisite/Model/Plugin.php(1) : eval()'d code on line 14`

**Comment by bentideswell** [comment] 2016-09-22 08:52
I have just released updates for FishPig_WordPress and FishPig_WordPress_Multisite that should fix this issue. I will close this for now but re-open if the issue isn't resolved.

You can download FishPig_WordPress_Multisite from your account on https://fishpig.co.uk/

**Closed by bentideswell** 2016-09-22 08:52 UTC
